version: '3.9'
services:
  server:
    build: ./server
    env_file: .env
    ports:
      - '5000:5000'
    depends_on:
      - db
  client:
    build: ./client
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - server
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
